### ISSUE TITLE
nat-gateway-scenarios.md

### ISSUE THREAD

**Issue by hernan-fernandez** [awsdocs/amazon-vpc-user-guide#100]
The NAT Gateway scenarios page doesn't describe an High availability architecture where an NAT Gateway is recommended in each availability zone to improve the applications availability and reduce the inter-az network charges.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
