### ISSUE TITLE
vpce-interface.md: Update limitations regarding peered VPC connections and instance types?

### ISSUE THREAD

**Issue by cvcrckt** [awsdocs/amazon-vpc-user-guide#16]
When I first read this:

> Interface endpoints can be accessed through intra-region VPC peering connections from Nitro instances. Interface endpoints can be accessed through inter-region VPC peering connections from any type of instance

... I thought it sounded more likely that the reverse would be true: that intra-region would be supported by all instance types, and inter-region would only be supported by Nitro instances.

I became curious and tested this with an intra-region VPC peering connection (us-east-2 <-> us-east-2) and an inter-region VPC peering connection (us-west-1 <-> us-east-2) and found that I could use an interface endpoint over both types of connections from both types of instances (non-Nitro and Nitro). Maybe that behavior is not supported with every combination of regions. If it is, then the doc should be updated.

**Comment by julieso** [comment]
Thanks for your question. My apologies for the delayed response. The documentation accurately described that limit at the time. However, we announced that we removed the restrictions on March 7: https://aws.amazon.com/about-aws/whats-new/2019/03/aws-privatelink-now-supports-access-over-vpc-peering/. Depending on where and when you tested, you might have been seeing the new behavior as it rolled out. In the HTML version of the docs, this has been edited to "An interface endpoint can be accessed through AWS VPN connections, AWS Direct Connect connections, and VPC peering connections." See https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html#vpce-interface-limitations.
