### ISSUE TITLE
Add Route Table example with tgw-

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-vpc-user-guide#18]
On page:
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html#route-tables-priority
we have several examples with igw-, pcx- etc. but no example with Transit Gateway using tgw- especially what's the route priority if we have route with say vgw- and tgw-

**Comment by browndjaz** [comment]
There is now a section that has a Transit Gateway example:
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html#route-tables-priority
