### ISSUE TITLE
Interface Endpoints that Support Endpoint Policies (API Gateway)

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-vpc-user-guide#23]
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html

For interface endpoints, only the following examples are listed: CodeBuild, CodeCommit, SNS, SQS.

Now, API Gateway is supported - should that be listed here as well?

https://aws.amazon.com/blogs/compute/introducing-amazon-api-gateway-private-endpoints/

**Comment by jsoncow** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-vpc-endpoint-policies.html

**Comment by browndjaz** [comment]
Hi,

I've updated the pages with all the services that support endpoints and enpoint policies.

https://github.com/awsdocs/amazon-vpc-user-guide/blob/master/doc_source/vpc-endpoints.md

https://github.com/awsdocs/amazon-vpc-user-guide/blob/master/doc_source/vpc-endpoints-access.md

Thanks,
Debbie Brown
