### ISSUE TITLE
VPC Secondary CIDR Blocks Rules require small corrections

### ISSUE THREAD

**Issue by khandhedia** [awsdocs/amazon-vpc-user-guide#29]
Secondary CIDRs in the VPC cannot:
1. have the *same* range as that of primary CIDR block.
2. have the larger range (more IP Addresses) as that of primary CIDR block.

If the primary CIDR is 10.0.0.0/24, secondary cannot be 10.0.0.0/25 as that will be an overlap. 
It can be 10.0.1.0/24 or similar.

**Comment by katerini** [comment]
Thanks! I've commented in your PR, so will resolve this issue and we can track the conversation in the PR.
