### ISSUE TITLE
missing hyperlinks in VPC_Internet_Gateway.html

### ISSUE THREAD

**Issue by infrastation** [awsdocs/amazon-vpc-user-guide#36]
Sometimes the HTML file has nothing where the source Markdown file has hyperlinks. I do not see how this could be fixed in Markdown.

1. ![Screenshot_2020-01-30_16-07-10](https://user-images.githubusercontent.com/900115/73469181-d7e05e00-437d-11ea-867c-043619f2aa55.png)
1. ![Screenshot_2020-01-30_16-07-20](https://user-images.githubusercontent.com/900115/73473623-fac24080-4384-11ea-9d3e-e9c1c2935d26.png)
1. ![Screenshot_2020-01-30_17-13-07](https://user-images.githubusercontent.com/900115/73473694-13325b00-4385-11ea-83dd-c3132cde98fb.png)
1. ![Screenshot_2020-01-30_17-13-19](https://user-images.githubusercontent.com/900115/73473705-19283c00-4385-11ea-8260-26dd96eddb8f.png)
1. ![Screenshot_2020-01-30_17-13-30](https://user-images.githubusercontent.com/900115/73473711-1fb6b380-4385-11ea-998b-cf1e393b2a18.png)
1. ![Screenshot_2020-01-30_17-13-47](https://user-images.githubusercontent.com/900115/73473722-247b6780-4385-11ea-9539-58f5551797cf.png)
1. ![Screenshot_2020-01-30_17-13-57](https://user-images.githubusercontent.com/900115/73473728-29401b80-4385-11ea-99db-85c122f10b05.png)

**Comment by infrastation** [comment]
Alright, that should be a complete list now.

**Comment by browndjaz** [comment]
Hi,

Thank you for the comment. The links are back on the page.

**Comment by infrastation** [comment]
As far as the live web-site goes, they are not, but let's leave this with you.
