### ISSUE TITLE
Services Affected by S3 VPC Endpoint Should Include EMR

### ISSUE THREAD

**Issue by hakenmt** [awsdocs/amazon-vpc-user-guide#39]
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html

The table in this section should include EMR based on these details:
https://docs.aws.amazon.com/emr/latest/ManagementGuide/private-subnet-iampolicy.html

There were also previously two other buckets listed for EMR that are not on the current version of the page, unsure if existing clusters may still need access to those for writing support logs.

"arn:aws:s3:::aws157-logs-prod-*/*"
"arn:aws:s3:::aws157-logs-prod/*"

**Comment by katerini** [comment]
Thanks for noting that - EMR has been added.
