### ISSUE TITLE
flow logs comment

### ISSUE THREAD

**Issue by gregbo** [awsdocs/amazon-vpc-user-guide#49]
IMO, it is unfortunate that the flow log record format can't be changed midstream.  If something like the [W3C extended log format](https://www.w3.org/TR/WD-logfile.html) was supported, the software that generates the flow logs could indicate a format change by inserting a comment record with the change (such as #Fields:).  Any software that processes the logs could check for the presence of the format change record, and react accordingly.  This provides flexibility for both log record generators and processors.

I can see that there could be concern about overhead (e.g. having to check each record for a format change record).  Hopefully, this would be offset by judicious generation of log data.  For example, if most log records for a given flow are not applicable ('-'), perhaps it is best not to log that field at all, and indicate so in the first format log record.

**Comment by katerini** [comment]
Hello, thanks so much for your feedback. I've forwarded your comments to the relevant teams, and we will look into the option to change the log format for existing subscriptions.

In the meantime, I will resolve this issue as there are no doc updates needed at this point.

Thanks again!
