### ISSUE TITLE
Small glitch on Gateway VPC endpoints diagram

### ISSUE THREAD

**Issue by eze1981** [awsdocs/amazon-vpc-user-guide#51]
Hello, 

It seems to be a small issue on the network diagram on the Gateway VPC endpoints documentation. In the diagram, Subnet 1 is displayed with a lock as it was a private subnet. But, the routing table associated with it allows traffic through an internet gateway, making it public.

Gateway VPC endpoints: https://github.com/awsdocs/amazon-vpc-user-guide/blob/master/doc_source/vpce-gateway.md
The diagram URL is: http://docs.aws.amazon.com/vpc/latest/userguide/images/vpc-endpoint-s3-diagram.png

Regards,
Ezequiel

**Comment by katerini** [comment]
Hello, thanks for your comment! 
Traditionally, the networking diagrams in the VPC user guide always display a subnet with a lock icon, regardless of whether it's a public or private subnet. The intention isn't to imply internet vs no internet access, but rather to imply the security of a subnet in general (through security groups, network ACLs, etc).

We've continued with the same pattern, however, we're always happy to work on revising the diagrams if they are confusing, inconsistent, or if they're being interpreted differently. So thanks again for the feedback; we'll definitely take it into account.
