### ISSUE TITLE
Totally wrong architecture

### ISSUE THREAD

**Issue by parkybyang** [awsdocs/amazon-vpc-user-guide#64]
wrong architect, 
consumer vpc2 is consumer not a service provider,
ELB just sprays request but reversely transmit data back to client

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
