### ISSUE TITLE
AWS SQS Endpoint?

### ISSUE THREAD

**Issue by Jeeppler** [awsdocs/amazon-vpc-user-guide#9]
A list of [VPC Endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html) is available as part of this guide. However, I am can't see SQS in list of Endpoints or in the list of Gateways. Is there a way to expose AWS SQS to a VPC without going through the internet?

**Comment by julieso** [comment]
Yes, this list contains all services that you can access through a VPC endpoint at this time.
