### ISSUE TITLE
wrong ipv6 route table in vpc-migrate-ipv6.md

### ISSUE THREAD

**Issue by yuanl** [awsdocs/amazon-vpc-user-guide#91]
The figure below `After you've completed the steps, your VPC will have the following configuration.` show a wrong route table for private subnet.

In its following step: 
Step 2: Update your route tables -> To update your route table for a private subnet -> 5. **Choose Add route. For Destination**,
The Targe for ::/0 is a `egress-only internet gateway`.

But the above figure illustrates a NAT gateway. Should be a egress-only-internet-gateway.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
