### ISSUE TITLE
S3 Gateway policy doesn't support PrincipalAccount condition variable

### ISSUE THREAD

**Issue by amrali** [awsdocs/amazon-vpc-user-guide#94]
I wanted to scope down access for S3 Gateway using the `PrincipalAccount` condition variable as part of using it in combination of ECR interface endpoints to have ECS Fargate tasks pull images through the ECR endpoints. After a few days spinning my wheels over it, reached out to AWS support and after they replicated my environment they figured out that S3 Gateway doesn't support the `PrincipalAccount` condition variable.

I believe that this should go under limitations of the S3 Gateway endpoint part of the documentation. Is this the right place for something like this?

This also means that this section is wrong:

```
Example: Restrict access to users in a specific account

You can create a policy that restricts access to a specific account.

{
  "Sid": "AllowCallersFromAccount111122223333",
  "Effect": "Allow",
  "Principal": "*",
  "Action": "*",
  "Resource": "*",
  "Condition": {
    "StringEquals": {
      "aws:PrincipalAccount": "111122223333"
    }
  }
}
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
